---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackrox
  namespace: openshift-gitops
spec:
  destination:
    namespace: stackrox-central-services
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rhacs/helm-dependency/
    repoURL: https://github.com/clustership/gitops-day2.git
    targetRevision: HEAD
  sync:
    comparedTo:
      destination:
        namespace: stackrox-central-services
        server: https://kubernetes.default.svc
      source:
        path: rhacs/helm-dependency/
        repoURL: https://github.com/clustership/gitops-day2.git
        targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
