# StackRox Central Services Chart - PUBLIC configuration values.
# These are the public values for the deployment of the StackRox Central Services chart.
# You can safely store this file in a source-code management system, as it doesnot contain
# sensitive information. It is recommended to reference this file via the '-f' option
# whenever running a 'helm upgrade' command.

stackrox-central-services:
  customize:
    other:
      securitycontextconstraints/*:
        annotations:
          argocd.argoproj.io/hook: PreSync
  env:
    openshift: true
    offlineMode: false
  central:
    disableTelemetry: false
    # change this admin password!
    adminPassword:
      htpasswd: "admin:$2y$05$dzvTp.xhc3Z9878TwFwpoOmYgiy.BsYglKAd/1LbIi/xuIETc2jk2"
    resources:
    # this is where you can adjust the requests down if you have smaller nodes
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    persistence:
      persistentVolumeClaim:
        claimName: "stackrox-db"
        size: "100Gi"
    exposure:
      route:
        enabled: true
  
  scanner:
    # IMPORTANT: If you do not wish to run StackRox Scanner, change the value on the following
    # line to "true".
    disable: false
